#pragma once

#define MAJOR_VERSION 0
#define MINOR_VERSION 0
#define PATCH_VERSION 1

#define PRE_RELEASE "April 17th, 2022"

#define BUILD "Irrelevant"

#define CORE_VERSION MAJOR_VERSION.MINOR_VERSION.PATCH_VERSION

#define SEMI_VERSION CORE_VERSION - PRE_RELEASE

#define CURRENT_COMPLETE_VERSION CORE_VERSION - BUILD
